### ISSUE TITLE
How to use FP16 for inference？

### ISSUE THREAD

**Issue by WuYiYiYi** [xiaomi-mlab/Orion#8]
Hello, how to use FP16 for inference? I'm using an RTX 3090 with 24GB VRAM， use fp32 with **torch.OutOfMemoryError: CUDA out of memory**.  Looking forward to your reply.

**Comment by Poley97** [comment]
We update a new cfg for **FP16** inference, which only requires **~17GB** VRAM. It should be able to perform an open-loop evaluation on an RTX 3090 GPU. However, considering that the **CARLA** engine also requires approximately **8GB** of VRAM to run, RTX 3090 may still encounter some difficulties in closed-loop evaluation.
Please check our latest commit.

**Comment by WuYiYiYi** [comment]
@Poley97 Thanks！When running the code with the cfg orion_stage3_fp16.py, the code throws an error. It appears that certain parts of the code are not fully compatible with FP16. Could you please review this issue? Looking forward to your feedback.
`[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/detectors/orion.py", line 347, in extract_feat
[rank0]:     img_feats = self.extract_img_feat(img)
[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/detectors/orion.py", line 329, in extract_img_feat
[rank0]:     img_feats = self.img_backbone(img)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/backbones/eva_vit.py", line 1009, in forward
[rank0]:     x = blk(x)   # b, h, w, c
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/backbones/eva_vit.py", line 859, in forward
[rank0]:     x = self._forward(x)
[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/backbones/eva_vit.py", line 841, in _forward
[rank0]:     x = self.attn(x)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/amax/workspace/sourc_code/Orion-main/mmcv/models/backbones/eva_vit.py", line 696, in forward
[rank0]:     x = self.proj(x)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/amax/miniforge3/envs/orion/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 117, in forward
[rank0]:     return F.linear(input, self.weight, self.bias)
[rank0]: RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half`

**Comment by Poley97** [comment]
Thank you for pointing out this issue! The problem has been fixed. Please check the latest commit.

**Comment by WuYiYiYi** [comment]
Thank you so much! The issue has been resolved.
